### ISSUE TITLE
Consider publishing to crates.io

### ISSUE THREAD

**Issue by Alvenix** [niroco/diesel_async_migrations#4]
I think this crate can be useful, it would be nice if it is available in crates.io

**Comment by Tanguille** [comment]
I agree, it's not convenient to use it via git.

**Comment by nicrosengren** [comment]
Yeah, it would be a lot easier if it was deployed to crates.io.

I've been skipping it to not pollute the diesel namespace since this is not affiliated with the diesel project.

I'll reconsider it!

**Comment by Alvenix** [comment]
I have migrated to using diesel [AsyncConnectionWrapper](https://docs.rs/diesel-async/0.4.1/diesel_async/async_connection_wrapper/type.AsyncConnectionWrapper.html#). Although I am not sure if it is as convenient.

**Comment by nicrosengren** [comment]
Might be a little late. But I've published the crate if it's still interesting :)
